<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML" />
    <PackageReference Include="Microsoft.ML.FastTree" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\Finance.Integrations.MarketAux\Finance.Integrations.MarketAux.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="MLModel\sentiment_data.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
