<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\Finance.Contracts\Finance.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\Finance.SharedKernel.Messaging\Finance.SharedKernel.Messaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.Core" />
    <PackageReference Include="Hangfire.InMemory" />
    <PackageReference Include="Hangfire.Redis.StackExchange" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
