<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.Azure.ServiceBus.Core" />
    <PackageReference Include="MassTransit.RabbitMQ" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Finance.SharedKernel.Logging\Finance.SharedKernel.Logging.csproj" />
  </ItemGroup>

</Project>
