<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.SemanticKernel" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\Finance.Contracts\Finance.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\Finance.Integrations.MarketAux\Finance.Integrations.MarketAux.csproj" />
    <ProjectReference Include="..\..\..\shared\Finance.SharedKernel.Messaging\Finance.SharedKernel.Messaging.csproj" />
  </ItemGroup>

</Project>
