<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="SendGrid" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\Finance.Contracts\Finance.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\Finance.SharedKernel.Messaging\Finance.SharedKernel.Messaging.csproj" />
    <ProjectReference Include="..\Finance.NotificationService.Persistence\Finance.NotificationService.Persistence.csproj" />
  </ItemGroup>

</Project>
